Title: Charles Edosa
logo: github pics.jpeg 
description: cyber security portfolio. # Fix hyphenation 
show_downloads: true # Fix spelling
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag # Add SEO plugin

email: edosacharles111@yahoo.com # Allow visitors to contact you
